
- name: "enhancement"
  color: "84b6eb"
  description: "✨ New features, content, or major mods added"

- name: "bug"
  color: "d73a4a"
  description: "🐛 Crash fixes, broken mods, errors"

- name: "tweak"
  color: "fbca04"
  description: "🛠️ Small adjustments and refinements"

- name: "balance"
  color: "c5def5"
  description: "⚖️ Gameplay and mechanical balancing"

- name: "other"
  color: "ededed"
  description: "🔧 Miscellaneous or uncategorized updates"

  - name: "📝 docs"
  color: "c2e0c6"
  description: "Documentation updates (README, guides, templates)"

