name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

changelog:
  categories:
    - title: "✨ Features"
      labels: ["enhancement"]
    - title: "🐛 Fixes"
      labels: ["bug"]
    - title: "🛠 Tweaks"
      labels: ["tweak"]
    - title: "⚖️ Balance"
      labels: ["balance"]
    - title: "🔧 Other"
      labels: ["other"]
    - title: "🔧 Other (Unlabeled)"
      labels: []   # Catch-all for PRs with no label

template: |
  # 🌿 Nymphs Savage World – v$NEXT_PATCH_VERSION

  ✨ A collaborative Skyrim modlist — immersive, magical, and consent-driven.  

  ---

  ## 📥 Downloads
  - **Wabbajack Installer File (.wabbajack):** [Download](INSERT-LINK-HERE)  
  - **Nexus Page:** [Nymphs Savage World on Nexus](https://www.nexusmods.com/skyrimspecialedition/mods/154913)  

  ---

  ## 🆕 What’s New in This Release

  $CHANGES

  ---

  ## ⚠️ Notes for Players
  - This list is still in **Alpha**: expect bugs, missing LODs, and performance quirks.  
  - Controller users: enable **“Nymphs - Controller”** mod at the bottom of your load order.  
  - First launch may show the wrong resolution (Windows DPI scaling) — fixed on restart.  
  - Combat settings require MCM tweaks (see Discord for recommended configs).  

  ---

  ## 🧰 Installation
  1. Download and install [Wabbajack](https://www.wabbajack.org/).  
  2. Select the **Nymphs Savage World** `.wabbajack` file.  
  3. Choose install/download directories (separate drives recommended).  
  4. Run install — then launch Skyrim SE via **SKSE** in MO2.  

  ---

  ## 👥 Credits
  Built with 💚 by **babyjaws, Rauty79, Julio005**  
  Special thanks to **backbeatN, Nyx, dbottle, Dlizzio, Herr Schtevie**  

  <p align="center">
    <em>Join our community: <a href="https://discord.gg/ezJVqBJvVj">Discord Server</a></em>
  </p>
