name: "PR Auto Labeler"

on:
  pull_request:
    types: [opened, edited, synchronize, unlabeled]

  schedule:
    - cron: "0 3 * * *" # runs daily at 03:00 UTC

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add default label if none is set
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pulls } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open"
            });

            for (const pr of pulls) {
              if (pr.labels.length === 0) {
                console.log(`Adding default label to PR #${pr.number}`);
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: pr.number,
                  labels: ["🔧 other"]
                });
              }
            }
